
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import mime from 'mime-types'; // You might need to install this or use simple lookup

// Load environment variables
const envProdPath = path.join(process.cwd(), '.env.production');
const envLocalPath = path.join(process.cwd(), '.env.local');

let envConfig;
if (fs.existsSync(envProdPath)) {
    console.log('Loading credentials from .env.production');
    envConfig = dotenv.parse(fs.readFileSync(envProdPath));
} else {
    console.log('Loading credentials from .env.local');
    envConfig = dotenv.parse(fs.readFileSync(envLocalPath));
}

const SUPABASE_URL = envConfig.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_KEY = envConfig.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
    console.error('Missing Supabase credentials');
    process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
    auth: { persistSession: false }
});

const MAPPING_FILE = path.join(process.cwd(), 'docs', 'image_mapping.json');
const IMAGES_DIR = path.join(process.cwd(), 'docs', 'extracted_images');

async function main() {
    console.log('--- Starting Image Upload ---');

    // 1. Ensure Bucket Exists
    const BUCKET_NAME = 'products';
    const { data: buckets, error: listError } = await supabase.storage.listBuckets();
    if (listError) {
        console.error('Error listing buckets:', listError);
        return;
    }

    let bucket = buckets.find(b => b.name === BUCKET_NAME);
    if (!bucket) {
        console.log(`Creating public bucket: ${BUCKET_NAME}`);
        const { data, error } = await supabase.storage.createBucket(BUCKET_NAME, {
            public: true,
            fileSizeLimit: 5242880, // 5MB
        });
        if (error) {
            console.error('Error creating bucket:', error);
            return;
        }
        bucket = data; // Although data might be string or object depending on version, usually it returns name
    } else {
        console.log(`Bucket '${BUCKET_NAME}' already exists.`);
    }

    // 2. Process Mapping
    const mapping = JSON.parse(fs.readFileSync(MAPPING_FILE, 'utf-8'));
    console.log(`Found ${mapping.length} items to process.`);

    // We need to fetch the actual Product IDs from the DB because the mapping 
    // was based on the JSON file, which might not have the UUIDs generated by Supabase (unless we upserted them with specific IDs, but we rely on gen_random_uuid).
    // Actually, looking at the import script, we did 'insert(data)'.
    // So we need to query the DB to match product names to IDs.

    console.log('Fetching products from DB to resolve UUIDs...');
    const { data: dbProducts, error: dbError } = await supabase
        .from('products')
        .select('id, name');

    if (dbError) {
        console.error('Error fetching products from DB:', dbError);
        return;
    }

    // Create a lookup map: Name -> ID
    const productMap = new Map();
    dbProducts.forEach(p => productMap.set(p.name, p.id));

    // Batch process
    const batchSize = 5;
    for (let i = 0; i < mapping.length; i += batchSize) {
        const batch = mapping.slice(i, i + batchSize);
        await Promise.all(batch.map(async (item) => {
            if (!item.product || !item.imageFile) return;

            const productName = item.product.name;
            const productId = productMap.get(productName);

            if (!productId) {
                console.warn(`Could not find UUID for product: ${productName}`);
                return;
            }

            const localFilePath = path.join(IMAGES_DIR, item.imageFile);
            if (!fs.existsSync(localFilePath)) {
                console.warn(`File not found: ${localFilePath}`);
                return;
            }

            const fileExt = path.extname(item.imageFile);
            const fileName = `${productId}${fileExt}`; // e.g. uuid.jpg
            const fileContent = fs.readFileSync(localFilePath);

            // Upload
            const { error: uploadError } = await supabase.storage
                .from(BUCKET_NAME)
                .upload(fileName, fileContent, {
                    contentType: 'image/' + fileExt.replace('.', ''),
                    upsert: true
                });

            if (uploadError) {
                console.error(`Failed to upload ${fileName}:`, uploadError.message);
                return;
            }

            // Get Public URL
            const { data: { publicUrl } } = supabase.storage
                .from(BUCKET_NAME)
                .getPublicUrl(fileName);

            // Update DB
            const { error: updateError } = await supabase
                .from('products')
                .update({ image_url: publicUrl })
                .eq('id', productId);

            if (updateError) {
                console.error(`Failed to update DB for ${productName}:`, updateError.message);
            } else {
                console.log(`Updated > ${productName.substring(0, 20)}...`);
            }
        }));
    }

    console.log('--- Upload Finished ---');
}

main();
